all: true
recursive: true
with-expecter: true

packages:
  gitlab.ent-dx.com/entangle/pull-update-publisher/fetcher:
  gitlab.ent-dx.com/entangle/pull-update-publisher/publisher:
  gitlab.ent-dx.com/entangle/pull-update-publisher/transactor:
