// Code generated by mockery v2.43.0. DO NOT EDIT.

package publisher

import mock "github.com/stretchr/testify/mock"

// MockITransactor is an autogenerated mock type for the ITransactor type
type MockITransactor struct {
	mock.Mock
}

type MockITransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITransactor) EXPECT() *MockITransactor_Expecter {
	return &MockITransactor_Expecter{mock: &_m.Mock}
}

// SendUpdate provides a mock function with given fields:
func (_m *MockITransactor) SendUpdate() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockITransactor_SendUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUpdate'
type MockITransactor_SendUpdate_Call struct {
	*mock.Call
}

// SendUpdate is a helper method to define mock.On call
func (_e *MockITransactor_Expecter) SendUpdate() *MockITransactor_SendUpdate_Call {
	return &MockITransactor_SendUpdate_Call{Call: _e.mock.On("SendUpdate")}
}

func (_c *MockITransactor_SendUpdate_Call) Run(run func()) *MockITransactor_SendUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockITransactor_SendUpdate_Call) Return(_a0 error) *MockITransactor_SendUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockITransactor_SendUpdate_Call) RunAndReturn(run func() error) *MockITransactor_SendUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockITransactor creates a new instance of MockITransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITransactor {
	mock := &MockITransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
