FROM golang:1.22.3-bookworm AS builder

WORKDIR /app
COPY go.mod go.sum ./

ENV APP_NAME=pull-update-publisher
ENV APP_BIN=/bin/${APP_NAME}

RUN go mod download

COPY . .

RUN BUILD_COMMIT=$(git rev-parse HEAD) CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-s -w' -o ${APP_BIN} -v ./cmd/pull-update-publisher

FROM alpine:3.19 AS runtime

ENV APP_NAME=pull-update-publisher
ENV APP_BIN=/bin/${APP_NAME}

COPY --from=builder ${APP_BIN} ${APP_BIN}
CMD ${APP_BIN}
