// Code generated by mockery v2.43.0. DO NOT EDIT.

package fetcher

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	fetcher "gitlab.ent-dx.com/entangle/pull-update-publisher/fetcher"
)

// MockIFetcher is an autogenerated mock type for the IFetcher type
type MockIFetcher struct {
	mock.Mock
}

type MockIFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIFetcher) EXPECT() *MockIFetcher_Expecter {
	return &MockIFetcher_Expecter{mock: &_m.Mock}
}

// GetFeedProofs provides a mock function with given fields: ctx, assetKey
func (_m *MockIFetcher) GetFeedProofs(ctx context.Context, assetKey string) (*fetcher.EntangleFeedProof, error) {
	ret := _m.Called(ctx, assetKey)

	if len(ret) == 0 {
		panic("no return value specified for GetFeedProofs")
	}

	var r0 *fetcher.EntangleFeedProof
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*fetcher.EntangleFeedProof, error)); ok {
		return rf(ctx, assetKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *fetcher.EntangleFeedProof); ok {
		r0 = rf(ctx, assetKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fetcher.EntangleFeedProof)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, assetKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIFetcher_GetFeedProofs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeedProofs'
type MockIFetcher_GetFeedProofs_Call struct {
	*mock.Call
}

// GetFeedProofs is a helper method to define mock.On call
//   - ctx context.Context
//   - assetKey string
func (_e *MockIFetcher_Expecter) GetFeedProofs(ctx interface{}, assetKey interface{}) *MockIFetcher_GetFeedProofs_Call {
	return &MockIFetcher_GetFeedProofs_Call{Call: _e.mock.On("GetFeedProofs", ctx, assetKey)}
}

func (_c *MockIFetcher_GetFeedProofs_Call) Run(run func(ctx context.Context, assetKey string)) *MockIFetcher_GetFeedProofs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIFetcher_GetFeedProofs_Call) Return(_a0 *fetcher.EntangleFeedProof, _a1 error) *MockIFetcher_GetFeedProofs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIFetcher_GetFeedProofs_Call) RunAndReturn(run func(context.Context, string) (*fetcher.EntangleFeedProof, error)) *MockIFetcher_GetFeedProofs_Call {
	_c.Call.Return(run)
	return _c
}

// GetSpotterFeedsProofs provides a mock function with given fields: ctx, spotterID, assetKeys
func (_m *MockIFetcher) GetSpotterFeedsProofs(ctx context.Context, spotterID string, assetKeys []string) (*fetcher.EntangleFeedsProofs, error) {
	ret := _m.Called(ctx, spotterID, assetKeys)

	if len(ret) == 0 {
		panic("no return value specified for GetSpotterFeedsProofs")
	}

	var r0 *fetcher.EntangleFeedsProofs
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (*fetcher.EntangleFeedsProofs, error)); ok {
		return rf(ctx, spotterID, assetKeys)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) *fetcher.EntangleFeedsProofs); ok {
		r0 = rf(ctx, spotterID, assetKeys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fetcher.EntangleFeedsProofs)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, spotterID, assetKeys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIFetcher_GetSpotterFeedsProofs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSpotterFeedsProofs'
type MockIFetcher_GetSpotterFeedsProofs_Call struct {
	*mock.Call
}

// GetSpotterFeedsProofs is a helper method to define mock.On call
//   - ctx context.Context
//   - spotterID string
//   - assetKeys []string
func (_e *MockIFetcher_Expecter) GetSpotterFeedsProofs(ctx interface{}, spotterID interface{}, assetKeys interface{}) *MockIFetcher_GetSpotterFeedsProofs_Call {
	return &MockIFetcher_GetSpotterFeedsProofs_Call{Call: _e.mock.On("GetSpotterFeedsProofs", ctx, spotterID, assetKeys)}
}

func (_c *MockIFetcher_GetSpotterFeedsProofs_Call) Run(run func(ctx context.Context, spotterID string, assetKeys []string)) *MockIFetcher_GetSpotterFeedsProofs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockIFetcher_GetSpotterFeedsProofs_Call) Return(_a0 *fetcher.EntangleFeedsProofs, _a1 error) *MockIFetcher_GetSpotterFeedsProofs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIFetcher_GetSpotterFeedsProofs_Call) RunAndReturn(run func(context.Context, string, []string) (*fetcher.EntangleFeedsProofs, error)) *MockIFetcher_GetSpotterFeedsProofs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIFetcher creates a new instance of MockIFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIFetcher {
	mock := &MockIFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
